name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list
        run: |
          pwd
          ls
      - name: checkout
        uses: actions/checkout@v2
      - name: listAgain
        run: |
          pwd
          ls
